language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
  - "echo $PYTHONPATH"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/"
  - "export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/"
  - "sudo ./manage.py test board accounts --settings=test_settings"