language: python
python:
  - "2.6"
  - "2.7"
services: mysql
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install mysql-python --use-mirrors"
before_script:
  - mysql -e 'create database whiteboard;'
  - python manage.py syncdb --noinput
# command to run tests
script:  "./manage.py test board accounts --settings=test_settings"